### ISSUE TITLE
During test run in project which uses starterra-tool-dapp as dependency show console.error

### ISSUE THREAD

**Issue by Mskalba** [starterra/starterra-tool-dapp#44]
After setuping tests and running it, the tests pass, but console.error from Material UI is displayed:

```
  console.error
    Material-UI: the createMuiTheme function was renamed to createTheme.
    
    You should use `import { createTheme } from '@material-ui/core/styles'`

    > 1 | import { NetworkInfo, Tokens, Wallet, WalletProvider } from "@starterra/starterra-tool-dapp";
        | ^
      2 | // import '@starterra/starterra-tool-dapp/dist/index.css'
      3 |
      4 | const avaliableNetworks: Record<string, NetworkInfo> = {

      at Object.createMuiTheme (node_modules/@material-ui/core/styles/createTheme.js:114:15)
      at Object.<anonymous> (node_modules/@starterra/starterra-tool-dapp/src/index.tsx:29:15)
      at Object.<anonymous> (src/App.tsx:1:1)
```

**Comment by nocmar** [comment]
CreateTheme comes form v5 version of materail-ui which is currently in alpha stage according to doc: https://www.npmjs.com/package/@material-ui/core. In my opinion we should stay with v4 version for now

**Comment by Mskalba** [comment]
@nocmar I agree. But why do we see that console.error?

**Comment by nocmar** [comment]
please use material ui in version  "@material-ui/core": "4.11.4" to avoid this error, we will suport createTheme in the next versions
